In [1]:
import pandas as pd
df = pd.read_excel("upwork_messy_data_cleaning_practice_200_rows.xlsx", sheet_name="Raw_Data")

In [2]:
df.head()

,Customer ID,Full Name,E-mail,Phone Number,Country,City,Join Date,Last Purchase,Age,Spend (USD),Subscribed?,Segment,Source File,Notes
0,CUST-1001,LIAM BROWN,LIAM.BROWN@EXAMPLE.ORG,443389083863,uk,Liverpool,05/17/2022,08/09/2022,29,NaN,Yes,Priority,web_form.xlsx,called twice
1,CUST-1002,Mary Turner,MARY.TURNER@YAHOO.COM,+1 341 316 4752,America,Atlanta,"Jun 11, 2021","Mar 20, 2022",unknown,7052.5,Active,enterprise,web_form.xlsx,left voicemail
2,CUST-1003,Mary Thomas,mary_thomas@yahoo.com,7242388496,CA,MONTREAL,2023-04-02,17/08/2023,25,1805.19,No,Corp,legacy_contacts.csv,requested invoice
3,CUST-1004,Robert Campbell,robertcampbell15@outlook.com,07048 281489,united kingdom,Edinburgh,"Oct 29, 2025",NaN,NaN,5787.2,TRUE,vip,crm_export_a.csv,duplicate from legacy file
4,cust 1005,William Taylor,william_taylor@yahoo.com,08346578713,united kingdom,glasgow,2025-07-30,2025-09-03,55,6513.11,Yes,Small Business,web_form.xlsx,wants weekend calls

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    200 non-null    str
 1    Full Name     200 non-null    str
 2   E-mail         190 non-null    str
 3   Phone Number   200 non-null    str
 4   Country        200 non-null    str
 5   City           200 non-null    str
 6   Join Date      200 non-null    str
 7   Last Purchase  176 non-null    str
 8   Age            171 non-null    object
 9   Spend (USD)    181 non-null    object
 10  Subscribed?    200 non-null    str
 11  Segment        200 non-null    str
 12  Source File    200 non-null    str
 13  Notes          164 non-null    str
dtypes: object(2), str(12)
memory usage: 22.0+ KB

In [4]:
df.isnull().sum()

Customer ID       0
 Full Name        0
E-mail           10
Phone Number      0
Country           0
City              0
Join Date         0
Last Purchase    24
Age              29
Spend (USD)      19
Subscribed?       0
Segment           0
Source File       0
Notes            36
dtype: int64

In [5]:
df.to_csv("clean_customer_data.csv", index=False)

In [6]:
df = pd. DataFrame(df)
df. head()
column_list = list(df.columns)
column_list

['Customer ID ',
 ' Full Name',
 'E-mail',
 'Phone Number',
 'Country ',
 'City',
 'Join Date',
 'Last Purchase',
 'Age ',
 'Spend (USD)',
 'Subscribed?',
 'Segment',
 'Source File',
 'Notes']

In [7]:
df.dtypes

Customer ID         str
 Full Name          str
E-mail              str
Phone Number        str
Country             str
City                str
Join Date           str
Last Purchase       str
Age              object
Spend (USD)      object
Subscribed?         str
Segment             str
Source File         str
Notes               str
dtype: object

In [8]:
df.isna().sum()

Customer ID       0
 Full Name        0
E-mail           10
Phone Number      0
Country           0
City              0
Join Date         0
Last Purchase    24
Age              29
Spend (USD)      19
Subscribed?       0
Segment           0
Source File       0
Notes            36
dtype: int64

In [9]:
df.head(10)

,Customer ID,Full Name,E-mail,Phone Number,Country,City,Join Date,Last Purchase,Age,Spend (USD),Subscribed?,Segment,Source File,Notes
0,CUST-1001,LIAM BROWN,LIAM.BROWN@EXAMPLE.ORG,443389083863,uk,Liverpool,05/17/2022,08/09/2022,29,NaN,Yes,Priority,web_form.xlsx,called twice
1,CUST-1002,Mary Turner,MARY.TURNER@YAHOO.COM,+1 341 316 4752,America,Atlanta,"Jun 11, 2021","Mar 20, 2022",unknown,7052.5,Active,enterprise,web_form.xlsx,left voicemail
2,CUST-1003,Mary Thomas,mary_thomas@yahoo.com,7242388496,CA,MONTREAL,2023-04-02,17/08/2023,25,1805.19,No,Corp,legacy_contacts.csv,requested invoice
3,CUST-1004,Robert Campbell,robertcampbell15@outlook.com,07048 281489,united kingdom,Edinburgh,"Oct 29, 2025",NaN,NaN,5787.2,TRUE,vip,crm_export_a.csv,duplicate from legacy file
4,cust 1005,William Taylor,william_taylor@yahoo.com,08346578713,united kingdom,glasgow,2025-07-30,2025-09-03,55,6513.11,Yes,Small Business,web_form.xlsx,wants weekend calls
5,CUST-1006,David Baker,david_baker@company.co.uk,440106513338,UK,Cardiff,"Mar 26, 2024","Nov 23, 2024",36,6672.5,N,retail,legacy_contacts.csv,called twice
6,CUST-1007,David Green,david_green@example.org,4309 805 00,Australia,Melbourne,2023-02-16,2023-02-17,45,USD 2265.25,No,Small Business,march_upload.csv,missing postcode
7,CUST-1008,Isla Taylor,itaylor@outlook.com,04751-079911,UK,Cardiff,03/03/2024,25-Nov-2024,41,7945.98,Active,Enterprise,march_upload.csv,follow up in Q2
8,CUST-1009,Grace Brown,gracebrown27@outlook.com,4016 400 52,AUS,Melbourne,2022-06-26,24/08/2022,27,6314.41,Y,consumer,crm_export_b.csv,NaN
9,CUST-1010,Mr Olivia Jones,ojones@example.org,322602563,AUS,melbourne,28-Oct-2024,04/03/2025,63,887.2,FALSE,VIP,web_form.xlsx,missing postcode

In [10]:
df[df["E-mail"].isna()]

,Customer ID,Full Name,E-mail,Phone Number,Country,City,Join Date,Last Purchase,Age,Spend (USD),Subscribed?,Segment,Source File,Notes
18,CUST-1019,MIA ROBERTS,NaN,0842710947,United States,DALLAS,2024-05-07,2024-09-28,27,"$7,079.85",yes,RETAIL,crm_export_a.csv,duplicate from legacy file
51,CUST-1052,Laura Roberts,NaN,+1 986 652 4041,usa,seattle,"Sep 02, 2022","Oct 01, 2023",NaN,5996.08,yes,Small Business,crm_export_b.csv,NaN
167,CUST-1168,Robert Taylor,NaN,08275670431,Gb,Birmingham,"Aug 14, 2022",12/17/2023,25,942.96,yes,Small business,legacy_contacts.csv,NaN
176,CUST-1177,CHRIS BROWN,NaN,9473864631,America,Dallas,2021-10-06,"Jun 16, 2022",NaN,"$5,994.64",1,Retail,crm_export_b.csv,NaN
185,CUST-1126,John Baker,NaN,03894 484631,United Kingdom,sheffield,"Dec 12, 2025",NaN,NaN,NaN,yes,Enterprise,crm_export_a.csv,missing postcode possible dup
188,CUST-1077,Sophia Green,NaN,01463-031617,Gb,EDINBURGH,2024-01-07,2024-11-17,30,2369.31,Active,smb,web_form.xlsx,follow up in Q2 possible dup
189,CUST 1052,Laura Roberts,NaN,+19866524041,usa,seattle,"Sep 02, 2022","Oct 01, 2023",NaN,5996.08,yes,Small Business,legacy_contacts.csv,NaN
192,CUST-1147,SARAH BROWN,NaN,448452182307,UK,London,"May 12, 2025",08/23/2025,NaN,3780.42,Active,smb,legacy_contacts.csv,wants weekend calls possible dup
193,CUST-1160,Chloe King,NaN,00613878293,United Kingdom,Sheffield,not sure,19/06/2022,55,5474.31,Yes,premium,crm_export_a.csv,possible dup
198,CUST-1078,Chloe Roberts,NaN,8507925241,Canada,TORONTO,2025-04-29,NaN,22,2857.57,Y,SMB,march_upload.csv,duplicate from legacy file possible dup

In [11]:
df_work = df.copy()

In [12]:
df_work.columns

Index(['Customer ID ', ' Full Name', 'E-mail', 'Phone Number', 'Country ',
       'City', 'Join Date', 'Last Purchase', 'Age ', 'Spend (USD)',
       'Subscribed?', 'Segment', 'Source File', 'Notes'],
      dtype='str')

In [13]:
df_work = df_work.replace(["", " ", "unknown", "N/A", "NULL"], pd.NA)

In [14]:
df_work.isna().sum()

Customer ID       0
 Full Name        0
E-mail           10
Phone Number      0
Country           0
City              0
Join Date         0
Last Purchase    24
Age              34
Spend (USD)      19
Subscribed?       0
Segment           0
Source File       0
Notes            36
dtype: int64

In [15]:
df.columns

Index(['Customer ID ', ' Full Name', 'E-mail', 'Phone Number', 'Country ',
       'City', 'Join Date', 'Last Purchase', 'Age ', 'Spend (USD)',
       'Subscribed?', 'Segment', 'Source File', 'Notes'],
      dtype='str')

In [16]:
df["E-mail"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198     True
199    False
Name: E-mail, Length: 200, dtype: bool

In [17]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [21]:
df.columns

Index(['customer_id', 'full_name', 'e-mail', 'phone_number', 'country', 'city',
       'join_date', 'last_purchase', 'age', 'spend_(usd)', 'subscribed?',
       'segment', 'source_file', 'notes'],
      dtype='str')

In [19]:
df["country"] = df["country"].str.strip().str.lower()

In [20]:
df["country"].value_counts(dropna=False)

country
united kingdom    38
uk                26
gb                26
u.k.              16
canada            16
united states     13
america           10
aus               10
u.s.              10
ca                 8
australia          8
usa                7
us                 5
au                 4
can                3
Name: count, dtype: int64